version: '3.7'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - ${SERVER_PORT}:80
    volumes:
     - ../:/var/www/html
     - /var/www/html/vendor
     - /var/www/html/docker/data
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
  mysql:
    image: mysql:8
    command: --max_allowed_packet=92505856 --ssl=0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data:/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PMA_PORT}:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: ${MYSQL_PORT}
